var stateData = {
	md: {
		Name: 'Monkey D. Luffy',
		Occupation: 'Captain',
		Residence: 'Foosha Village',
		Age: '19',
		Birthday: 'May 5th',
		Bounty: '500,000,000 Berries',
		DevilFruit: 'Gum-Gum Fruit',
		Alias: 'Straw Hat',
		Affiliation: 'Straw Hat Pirates',
		Status: 'Alive'
	},
	nw: {
		Name: 'Monkey D. Luffy',
		Occupation: 'Captain',
		Residence: 'Foosha Village',
		Age: '19',
		Birthday: 'May 5th',
		Bounty: '500,000,000 Berries',
		DevilFruit: 'Gum-Gum Fruit',
		Alias: 'The Paramecia',
		Affiliation: 'Straw Hat Pirates',
		Status: 'Alive'
	},
	rz: {
		Name: 'Roronoa Zoro',
		Occupation: 'Swordsman, Former Bounty Hunter',
		Residence: 'Shimotsuki Village',
		Age: '21',
		Birthday: 'November 11th',
		Bounty: '320,000,000 Berries',
		DevilFruit: 'None',
		Alias: 'Pirate Hunter Zoro',
		Affiliation: 'Straw Hat Pirates',
		Status: 'Alive'
	},
	nm: {
		Name: 'Nami',
		Occupation: 'Navigator, Thief',
		Residence: 'Cocoyasi Village',
		Age: '20',
		Birthday: 'July 3rd',
		Bounty: '66,000,000 Berries',
		DevilFruit: 'None',
		Alias: 'Cat Thief',
		Affiliation: 'Straw Hat Pirates',
		Status: 'Alive'
	},
	up: {
		Name: 'Usopp',
		Occupation: 'Sniper',
		Residence: 'Syrup Village',
		Age: '19',
		Birthday: 'April 1st',
		Bounty: '200,000,000 Berries',
		DevilFruit: 'None',
		Alias: 'Sogeking, King of Snipers',
		Affiliation: 'Straw Hat Pirates',
		Status: 'Alive'
	},
	sj: {
		Name: 'Sanji',
		Occupation: 'Cook',
		Residence: 'Baratie',
		Age: '21',
		Birthday: 'March 2nd',
		Bounty: '177,000,000 Berries',
		DevilFruit: 'None',
		Alias: 'Mr.Prince, Black Leg Sanji',
		Affiliation: 'Straw Hat Pirates',
		Status: 'Alive'
	},
	nr: {
		Name: 'Nico Robin',
		Occupation: 'Archaeologist, Former Assassin',
		Residence: 'Ohara',
		Age: '30',
		Birthday: 'February 6th',
		Bounty: '130,000,000 Berries',
		DevilFruit: 'Hana-Hana Fruit',
		Alias: 'Devil Child, Miss All Sunday',
		Affiliation: 'Straw Hat Pirates',
		Status: 'Alive'
	},
	bk: {
		Name: 'Brook',
		Occupation: 'Swordsman, Musician',
		Residence: 'Florian Triangle',
		Age: '90',
		Birthday: 'April 3rd',
		Bounty: '83,000,000 Berries',
		DevilFruit: 'Yomi-Yomi Fruit',
		Alias: 'Humming Brook, Soul King',
		Affiliation: 'Straw Hat Pirates',
		Status: 'Alive'
	},
	fk: {
		Name: 'Franky',
		Occupation: 'Shipwright',
		Residence: 'Water 7',
		Age: '36',
		Birthday: 'March 9th',
		Bounty: '94,000,000 Berries',
		DevilFruit: 'None',
		Alias: 'Cutty Flam',
		Affiliation: 'Straw Hat Pirates',
		Status: 'Alive'
	},
	tc: {
		Name: 'Tony Tony Chopper',
		Occupation: 'Doctor',
		Residence: 'Drum Island',
		Age: '17',
		Birthday: 'December 24th',
		Bounty: '100 Berries',
		DevilFruit: 'Human-Human Fruit',
		Alias: 'Chobro',
		Affiliation: 'Straw Hat Pirates',
		Status: 'Alive'
	},
	gm: {
		Name: 'Going Merry',
		Occupation: 'Caravel Class Ship',
		Residence: 'Syrup Village',
		Age: 'N/A',
		Birthday: 'N/A',
		Bounty: 'N/A',
		DevilFruit: 'None',
		Alias: 'Merry, Klabautermann',
		Affiliation: 'Straw Hat Pirates',
		Status: 'Destroyed'
	},
	ts: {
		Name: 'Thousand Sunny',
		Occupation: 'Brig Sloop Ship',
		Residence: 'Water 7',
		Age: 'N/A',
		Birthday: 'N/A',
		Bounty: 'None',
		DevilFruit: 'None',
		Alias: 'N/A',
		Affiliation: 'Straw Hat Pirates',
		Status: 'Alive'
	},

};
